spring:
  application:
    name: eureka-discovery-service

server:
  port: 8086
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:8086/eureka
